// Mocks generated by Mockito 5.4.2 from annotations
// in cariro_implant_academy/test/data/patients/patientSearch/repositories/addOrRemoveMyPatientsRepoImpl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cariro_implant_academy/features/patient/data/datasources/addOrRemoveMyPatientsDataSource.dart'
    as _i2;
import 'package:cariro_implant_academy/features/patient/domain/usecases/addRangeToMyPatientsUseCase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AddOrRemoveMyPatientsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddOrRemoveMyPatientsDataSource extends _i1.Mock
    implements _i2.AddOrRemoveMyPatientsDataSource {
  MockAddOrRemoveMyPatientsDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> addToMyPatientsRange(_i4.AddRangePatientsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToMyPatientsRange,
          [params],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> addToMyPatients(int? id) => (super.noSuchMethod(
        Invocation.method(
          #addToMyPatients,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> removeFromMyPatients(int? id) => (super.noSuchMethod(
        Invocation.method(
          #removeFromMyPatients,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
