// Mocks generated by Mockito 5.4.2 from annotations
// in cariro_implant_academy/test/domain/patient/patientSearch/useCases/addRangeToMyPatientsUseCase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cariro_implant_academy/core/error/failure.dart' as _i5;
import 'package:cariro_implant_academy/features/patient/domain/repositories/addOrRemoveMyPatientsRangeRepo.dart'
    as _i3;
import 'package:cariro_implant_academy/features/patient/domain/usecases/addRangeToMyPatientsUseCase.dart'
    as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddOrRemoveMyPatientsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddOrRemoveMyPatientsRepo extends _i1.Mock
    implements _i3.AddOrRemoveMyPatientsRepo {
  MockAddOrRemoveMyPatientsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> addToMyPatientsRange(
          _i6.AddRangePatientsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToMyPatientsRange,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #addToMyPatientsRange,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> addToMyPatients(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToMyPatients,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #addToMyPatients,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> removeFromMyPatients(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromMyPatients,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #removeFromMyPatients,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
